language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - pyenv global 3.7
  - pip install awscli
  - npm install -g @lhci/cli@0.3.x
script:
  - npm test
  - npm run build
deploy:
  - provider: s3
    on:
      all_branches: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $BUCKET_NAME
    skip_cleanup: true
    local_dir: build
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
after_success:
  - lhci autorun --upload.target=temporary-public-storage